version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: markdb
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4
    container_name: dage-redis
    ports:
      - "6379:6379"
    restart: unless-stopped


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
