spring:
  application:
    name: "DageBot"
  datasource:
    url: "jdbc:postgresql://localhost:5432/markdb"
    username: "user"
    password: "example"
  jpa:
    generate-ddl: true
    show-sql: true
  messages:
    basename: messages
    encoding: UTF-8
  data:
    redis:
      host: "localhost"
      port: 6379

server:
  port: 8081

telegram:
  username: "Dage59Bot"
  token: "${DAGEBOT_TOKEN}"
  use-webhook: false
  max-activities: 3